### PR TITLE
I don't know what I am doing. Pull request?

### PR DESCRIPTION
**Pull request by meagan7**

### CODE REVIEW

**Comment by danielalbertjeffery** [comment]
Hey Meagan,

Those .DS_Store are hidden configuration files ... generally you wouldn't
want those to be stored on GitHub.

Also you are trying to store images ... I'm not sure if that is a common
thing to version control - though perhaps it is for some.

**Comment by meagan7** [comment]
Hmm so the .ds_store files have come up because I've added images? 
Where do people store their images if they want to keep a back up of their files? I think I can understand the issue as you can't merge images.

**Comment by danielalbertjeffery** [comment]
.DS_store files are OSX settings files ... I think they keep your 'folder'
settings.

I am not really sure about keeping backups of images ... sounds like
something that a graphics application might handle well :)

**Comment by cyber2024** [comment]
small images in version control are fine, but you cant roll back changes... and if you have a large asset folder then you may be up for some large uploads/downlaods. So best to avoid.

I think the issue was with the gitignore file... but im not 100% on that

**Comment by danielalbertjeffery** [comment]
I think that if you are having problems, watch a whole course on Git/GitHub
:P

That's what I do. I find that it's easier to watch a whole few hour course,
rather than to constantly not know what is going on, and being very 'ad
hocky'.

I plan to do this at some point, I know the basics of Git/GitHub well, but
would benefit from some advanced usage skills :) There are a few good ones
out there ... I might watch the Code School ones.

**Comment by danielalbertjeffery** [comment]
@meagan if you have a .gitignore file (notice that it is a hidden file
hence the dot) as Russ said, then you can add .DS_Store to that file and it
won't track it.

If you have node_modules you'd also add that etc :)

The idea is to not track things which are really large, or that aren't
really part of your project. So .DS_Store is an OSX configuration for
folder, i.e it stores your folder settings.

If you have anything that uses a node_module folder, then those can get
rather large, so if you included those it'd make the time to download it
quite large.

That's part of what a package.json file is for, it stores your
'dependencies' (files that your application relies on) and the version etc.

This is kind of more than you really need to know, but it just illustrates
the idea that there are some files that you don't want to track, and it's
wise to keep your repository low (as Russ said!)

**Pull request closed without merging**
