### PR TITLE
Meagan

### PR DESCRIPTION
**Pull request by meagan7**

### CODE REVIEW

**Comment by cyber2024** [comment]
Hi Meagan, The problem with this pull request is that your version of the website wasnt up to date with the master, so we need to merge your's with the master first in your repository, then make the pull request. This will mean that your branch will incorporate the changes that kate made before (blog.html and updated link).

**Comment by meagan7** [comment]
Hello there! 
So after two months of git hiatus I've come back. In the terminal I did: 'git merge master' and it has not failed. It says it is already up to date.

**Comment by meagan7** [comment]
I've tried this without success:
```git fetch origin
git checkout -b meagan origin/meagan
git merge master```

```git checkout master
git merge --no-ff meagan
git push origin master```

so I'll push another version to my profile and then close this request? :persevere:

**Comment by cyber2024** [comment]
I will fix it if you like

**Comment by cyber2024** [comment]
merged and pulled.
I hope that worked out how it was supposed to.

**Comment by meagan7** [comment]
It probably has. Thanks! :)

**Comment by cyber2024** [comment]
Meagan, can you please fix the blog button, link it to the blog.html, commit the change and push ?

**Pull request merged**
